services:
  example:
    image: saveapis-example:dev
    build:
      context: ..
      dockerfile: Examples/SaveApis.Example/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "80:80"