services:
  web:
    hostname: web
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    build:
      context: ..
      dockerfile: Example/SaveApis.Core.Example/Dockerfile
    environment:
      # Log Configuration
      - SAVEAPIS_LOG_LEVEL=Information

      # ASP.NET Core Configuration
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      
      # Hangfire Redis Configuration (#20)
      - HANGFIRE_REDIS_NAME=example
      - HANGFIRE_REDIS_HOST=redis
      - HANGFIRE_REDIS_PORT=6379
      - HANGFIRE_REDIS_DATABASE=0
      - HANGFIRE_REDIS_USERNAME=example
      - HANGFIRE_REDIS_PASSWORD=example
      - HANGFIRE_REDIS_SSL=False

      # JWT Configuration (#28)
      - JWT_ISSUER=example
      - JWT_AUDIENCE=example
      - JWT_KEY=yourRandomWith64OrMoreLengthKeyWhichShouldBeStoredSafetyAndShouldNotBeSharedWithOtherPeople
      - JWT_EXPIRATION_IN_HOURS=8
      
      # Entity Framework Core Configuration (#42)
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=example
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      
      # EasyCaching Configuration (#40)
      - EASYCACHING_REDIS_HOST=redis
      - EASYCACHING_REDIS_PORT=6379
      - EASYCACHING_REDIS_DATABASE=1
      - EASYCACHING_REDIS_BUS_DATABASE=2
    ports:
      - "80:80"
  redis:
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
  mysql:
    hostname: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1s
      start_period: 5s

volumes:
  redis-data:
  mysql-data: