services:
  web:
    build:
      context: ..
      dockerfile: Example/SaveApis.Core.Example/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - 80:80