name: CD
on:
  push:
    branches:
      - main
    paths:
      - CHANGELOG.md
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0.x
      - name: Restore Dependencies
        run: dotnet restore SaveApis.Core/SaveApis.Core.csproj
      - name: Build
        run: dotnet build --no-restore --nologo --configuration Release SaveApis.Core/SaveApis.Core.csproj
      - name: Package
        run: dotnet pack --no-build --no-restore --nologo --configuration Release --output artifact SaveApis.Core/SaveApis.Core.csproj
      - name: Publish
        run: dotnet nuget push artifact/*.nupkg --source https://nuget.pkg.github.com/SaveApis/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
