name: CI
on:
  push:
    paths:
      - 'SaveApis.Core/**'
      - 'Tests/**'
      - '.github/workflows/ci.yml'
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: self-hosted
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Super-linter
        uses: super-linter/super-linter@v7.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CSHARP: true
          VALIDATE_GITHUB_ACTIONS: true
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 9.0.x
      - name: Add nuget sources
        run: |
          dotnet nuget add source ${{ secrets.HANGFIRE_ACE_URL }} --name Hangfire.ACE --username ${{ secrets.HANGFIRE_ACE_USER }} --password ${{ secrets.HANGFIRE_ACE_TOKEN }} --store-password-in-clear-text
          dotnet nuget add source ${{ secrets.HANGFIRE_PRO_URL }} --name Hangfire.Pro --username ${{ secrets.HANGFIRE_PRO_USER }} --password ${{ secrets.HANGFIRE_PRO_TOKEN }} --store-password-in-clear-text
      - name: Restore Dependencies
        run: dotnet restore SaveApis.Core/SaveApis.Core.csproj
      - name: Build
        run: dotnet build --no-restore --nologo --configuration Release SaveApis.Core/SaveApis.Core.csproj
